version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    container_name: proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"